# Generated by Django 3.2.3 on 2021-05-26 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20210526_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='day_lecture',
        ),
    ]
