# Generated by Django 3.2.3 on 2021-05-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_remove_lecture_day_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='student',
        ),
    ]
