# Generated by Django 3.2.3 on 2021-05-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='pupil',
        ),
    ]
